In [1]:
MODEL_ID = "ensemble"   # or "comparison"
ROLE = "eval"

import logging
from datetime import datetime
import pathlib
import pandas as pd

# ============================================
# 1) Choose a RUN_ID
# ============================================
RUN_ID = datetime.now().strftime("%m_%d_%H_%M")

RUN_ID = "12_07_07_30"

ANALYSIS_TYPE = "evaluate"


def setup_logger(
    run_id: str,
    model_id: str,
    role: str,
    log_dir: str = "logs",
    analysis_type: str = ANALYSIS_TYPE,
) -> logging.Logger:
    """
    Create a logger that writes to both stdout and a log file.

    - Logger name:  "<analysis_type>_<run_id>_<model_id>_<role>"
    - Log file:     "log_<analysis_type>_<run_id>_<model_id>.log" in `log_dir`
      (shared by all notebooks for the same model & run & analysis_type).
    """
    log_path = pathlib.Path(log_dir)
    log_path.mkdir(exist_ok=True)

    logger_name = f"{analysis_type}_{run_id}_{model_id}_{role}"
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.INFO)
    logger.propagate = False  

    # Avoid adding handlers multiple times if the cell is re-run
    if not logger.handlers:
        # Common formatter for both handlers
        formatter = logging.Formatter(
            fmt="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
            datefmt="%Y-%m-%dT%H:%M:%S",
        )

        # Stream handler (stdout)
        stream_handler = logging.StreamHandler()
        stream_handler.setLevel(logging.INFO)
        stream_handler.setFormatter(formatter)
        logger.addHandler(stream_handler)

        # File handler (one file per analysis_type + run_id + model_id)
        log_file = log_path / f"log_{analysis_type}_{run_id}_{model_id}.log"
        file_handler = logging.FileHandler(log_file)
        file_handler.setLevel(logging.INFO)
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)
        print(log_path)

    return logger

logger = setup_logger(RUN_ID, MODEL_ID, ROLE)
logger.info("Initialized logger.")

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: Initialized logger.

logs

In [2]:
# Cell 2: load metrics parquet files for LR, XGBoost, Random Forest

# Base paths relative to this notebook (2.evaluation)
lr_eval_path = pathlib.Path("model_evaluation_data")
xgb_eval_path = pathlib.Path("model_evaluation_data_xgboost")
rf_eval_path = pathlib.Path("model_evaluation_data_randomforest")

# If needed, change filenames here to match your RF eval notebook.
lr_metrics_file = lr_eval_path / "metrics_final_qc_model.parquet"
xgb_metrics_file = xgb_eval_path / "metrics_final_xgb_qc_model.parquet"
rf_metrics_file = rf_eval_path / "metrics_final_rf_qc_model.parquet"

logger.info("Loading metrics parquet files for LR, XGBoost, and Random Forest...")

metrics_lr = pd.read_parquet(lr_metrics_file)
metrics_xgb = pd.read_parquet(xgb_metrics_file)
metrics_rf = pd.read_parquet(rf_metrics_file)

logger.info(f"LR metrics shape: {metrics_lr.shape} from {lr_metrics_file}")
logger.info(f"XGB metrics shape: {metrics_xgb.shape} from {xgb_metrics_file}")
logger.info(f"RF metrics shape: {metrics_rf.shape} from {rf_metrics_file}")

logger.info(f"LR datasplits: {sorted(metrics_lr['datasplit'].unique().tolist())}")
logger.info(f"XGB datasplits: {sorted(metrics_xgb['datasplit'].unique().tolist())}")
logger.info(f"RF datasplits: {sorted(metrics_rf['datasplit'].unique().tolist())}")

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: Loading metrics parquet files for LR, XGBoost, and Random Forest...
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: LR metrics shape: (24, 6) from model_evaluation_data/metrics_final_qc_model.parquet
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: XGB metrics shape: (24, 6) from model_evaluation_data_xgboost/metrics_final_xgb_qc_model.parquet
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: RF metrics shape: (24, 6) from model_evaluation_data_randomforest/metrics_final_rf_qc_model.parquet
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: LR datasplits: ['shuffled_test', 'shuffled_train', 'shuffled_val', 'test', 'train', 'val']
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: XGB datasplits: ['shuffled_test', 'shuffled_train', 'shuffled_val', 'test', 'train', 'val']
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: RF datasplits: ['shuffled_test', 'shuffled_train', 'shuffled_val', 'test', 'train', 'val']

In [3]:
# Cell 3: helper functions for slicing and summarizing metrics

def get_test_allplates(df, model_name):
    """Non-shuffled test, all plates."""
    df_split = df.query("datasplit == 'test' and plate == 'all_plates'").copy()
    df_split["model"] = model_name
    return df_split[["model", "accuracy", "f1_score", "precision", "recall"]]

def get_test_by_plate(df, model_name):
    """Non-shuffled test, per plate."""
    df_plate = df.query(
        "datasplit == 'test' and not datasplit.str.contains('shuffled')",
        engine="python",
    ).copy()
    df_plate["model"] = model_name
    return df_plate[["model", "plate", "accuracy", "f1_score", "precision", "recall"]]

def summarize_split(df, split_name, model_name):
    """train/val/test for all plates."""
    df_s = df.query("datasplit == @split_name and plate == 'all_plates'").copy()
    df_s["model"] = model_name
    df_s["datasplit"] = split_name
    return df_s[["model", "datasplit", "accuracy", "f1_score", "precision", "recall"]]

def summarize_shuffled(df, model_name):
    """All shuffled splits for null performance."""
    df_shuf = df.query("datasplit.str.contains('shuffled')", engine="python").copy()
    df_shuf["model"] = model_name
    return df_shuf[["model", "datasplit", "plate", "accuracy", "f1_score"]]

In [4]:
# Cell 4: test-set performance comparison

logger.info("Computing test-set comparison (all plates and per plate)...")

test_lr = get_test_allplates(metrics_lr, "logistic_regression")
test_xgb = get_test_allplates(metrics_xgb, "xgboost")
test_rf = get_test_allplates(metrics_rf, "random_forest")

test_comparison = pd.concat([test_lr, test_xgb, test_rf], ignore_index=True)

logger.info("=== Test-set performance: all plates ===")
display(test_comparison)

logger.info("Test-set (all plates) comparison:")
for _, row in test_comparison.iterrows():
    logger.info(
        f"{row['model']}: accuracy={row['accuracy']:.4f}, "
        f"f1={row['f1_score']:.4f}, precision={row['precision']:.4f}, "
        f"recall={row['recall']:.4f}"
    )

# Per-plate test comparison
plate_lr = get_test_by_plate(metrics_lr, "logistic_regression")
plate_xgb = get_test_by_plate(metrics_xgb, "xgboost")
plate_rf = get_test_by_plate(metrics_rf, "random_forest")

plate_comparison = pd.concat([plate_lr, plate_xgb, plate_rf], ignore_index=True)

logger.info("=== Test-set performance: per plate ===")
display(plate_comparison.sort_values(["plate", "model"]))

logger.info("Computed per-plate test performance for all models.")

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: Computing test-set comparison (all plates and per plate)...
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: === Test-set performance: all plates ===

                 model  accuracy  f1_score  precision    recall
0  logistic_regression  0.789278  0.790501   0.785939  0.795117
1              xgboost  0.801486  0.802534   0.798319  0.806794
2        random_forest  0.756369  0.760313   0.748201  0.772824

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: Test-set (all plates) comparison:
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: logistic_regression: accuracy=0.7893, f1=0.7905, precision=0.7859, recall=0.7951
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: xgboost: accuracy=0.8015, f1=0.8025, precision=0.7983, recall=0.8068
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: random_forest: accuracy=0.7564, f1=0.7603, precision=0.7482, recall=0.7728
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: === Test-set performance: per plate ===

,model,plate,accuracy,f1_score,precision,recall
1,logistic_regression,Plate_3,0.846614,0.848126,0.839844,0.856574
9,random_forest,Plate_3,0.829681,0.833171,0.816444,0.850598
5,xgboost,Plate_3,0.884462,0.883768,0.889113,0.878486
2,logistic_regression,Plate_3_prime,0.813364,0.817156,0.800885,0.834101
10,random_forest,Plate_3_prime,0.771889,0.781457,0.750000,0.815668
6,xgboost,Plate_3_prime,0.811060,0.829876,0.754717,0.921659
3,logistic_regression,Plate_5,0.636771,0.630137,0.641860,0.618834
11,random_forest,Plate_5,0.576233,0.567506,0.579439,0.556054
7,xgboost,Plate_5,0.605381,0.574879,0.623037,0.533632
0,logistic_regression,all_plates,0.789278,0.790501,0.785939,0.795117
8,random_forest,all_plates,0.756369,0.760313,0.748201,0.772824
4,xgboost,all_plates,0.801486,0.802534,0.798319,0.806794

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: Computed per-plate test performance for all models.

In [5]:
# Cell 5: train / val / test comparison to check overfitting

logger.info("Summarizing train/val/test performance for all models...")

splits = ["train", "val", "test"]

summary_lr = pd.concat(
    [summarize_split(metrics_lr, s, "logistic_regression") for s in splits],
    ignore_index=True,
)

summary_xgb = pd.concat(
    [summarize_split(metrics_xgb, s, "xgboost") for s in splits],
    ignore_index=True,
)

summary_rf = pd.concat(
    [summarize_split(metrics_rf, s, "random_forest") for s in splits],
    ignore_index=True,
)

summary_all = pd.concat([summary_lr, summary_xgb, summary_rf], ignore_index=True)

print("=== Train / Val / Test comparison (all plates) ===")
display(summary_all.sort_values(["model", "datasplit"]))

for model_name in ["logistic_regression", "xgboost", "random_forest"]:
    df_m = summary_all.query("model == @model_name")
    train_acc = df_m.query("datasplit == 'train'")["accuracy"].iloc[0]
    test_acc = df_m.query("datasplit == 'test'")["accuracy"].iloc[0]
    gap = train_acc - test_acc
    logger.info(
        f"{model_name}: train_acc={train_acc:.4f}, "
        f"test_acc={test_acc:.4f}, train-test gap={gap:.4f}"
    )

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: Summarizing train/val/test performance for all models...

=== Train / Val / Test comparison (all plates) ===

                 model datasplit  accuracy  f1_score  precision    recall
2  logistic_regression      test  0.789278  0.790501   0.785939  0.795117
0  logistic_regression     train  0.846748  0.847041   0.845424  0.848665
1  logistic_regression       val  0.812945  0.813733   0.810319  0.817176
8        random_forest      test  0.756369  0.760313   0.748201  0.772824
6        random_forest     train  1.000000  1.000000   1.000000  1.000000
7        random_forest       val  0.765270  0.763942   0.768288  0.759644
5              xgboost      test  0.801486  0.802534   0.798319  0.806794
3              xgboost     train  0.981145  0.981151   0.980848  0.981454
4              xgboost       val  0.847614  0.847924   0.846201  0.849654

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: logistic_regression: train_acc=0.8467, test_acc=0.7893, train-test gap=0.0575
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: xgboost: train_acc=0.9811, test_acc=0.8015, train-test gap=0.1797
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: random_forest: train_acc=1.0000, test_acc=0.7564, train-test gap=0.2436

In [6]:
# Cell 6: shuffled performance (null baseline)

logger.info("Summarizing shuffled (null) performance for all models...")

shuf_lr = summarize_shuffled(metrics_lr, "logistic_regression")
shuf_xgb = summarize_shuffled(metrics_xgb, "xgboost")
shuf_rf = summarize_shuffled(metrics_rf, "random_forest")

shuffled_summary = pd.concat([shuf_lr, shuf_xgb, shuf_rf], ignore_index=True)

print("=== Shuffled (null) performance ===")
display(shuffled_summary.sort_values(["model", "datasplit", "plate"]))

for model_name in ["logistic_regression", "xgboost", "random_forest"]:
    df_m = shuffled_summary.query("model == @model_name")
    if df_m.empty:
        logger.info(f"{model_name}: no shuffled rows found.")
        continue
    avg_acc = df_m["accuracy"].mean()
    avg_f1 = df_m["f1_score"].mean()
    logger.info(
        f"{model_name}: mean shuffled accuracy={avg_acc:.4f}, "
        f"mean shuffled f1={avg_f1:.4f} over {len(df_m)} rows"
    )

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: Summarizing shuffled (null) performance for all models...

=== Shuffled (null) performance ===

                  model       datasplit          plate  accuracy  f1_score
9   logistic_regression   shuffled_test        Plate_3  0.491036  0.482270
10  logistic_regression   shuffled_test  Plate_3_prime  0.511521  0.506977
11  logistic_regression   shuffled_test        Plate_5  0.497758  0.502222
8   logistic_regression   shuffled_test     all_plates  0.497346  0.492769
5   logistic_regression  shuffled_train        Plate_3  0.496020  0.498380
6   logistic_regression  shuffled_train  Plate_3_prime  0.507864  0.501798
7   logistic_regression  shuffled_train        Plate_5  0.492643  0.482937
4   logistic_regression  shuffled_train     all_plates  0.498084  0.495495
1   logistic_regression    shuffled_val        Plate_3  0.499822  0.498280
2   logistic_regression    shuffled_val  Plate_3_prime  0.499726  0.497943
3   logistic_regression    shuffled_val        Plate_5  0.499381  0.498689
0   logistic_regression    shuffled_val     all_plates  0.499691  0.498298
33        random_forest   shuffled_test        Plate_3  0.522908  0.571939
34        random_forest   shuffled_test  Plate_3_prime  0.516129  0.571429
35        random_forest   shuffled_test        Plate_5  0.506726  0.554656
32        random_forest   shuffled_test     all_plates  0.517516  0.567760
29        random_forest  shuffled_train        Plate_3  0.497829  0.501675
30        random_forest  shuffled_train  Plate_3_prime  0.500761  0.498215
31        random_forest  shuffled_train        Plate_5  0.502790  0.502285
28        random_forest  shuffled_train     all_plates  0.499753  0.500987
25        random_forest    shuffled_val        Plate_3  0.503497  0.506887
26        random_forest    shuffled_val  Plate_3_prime  0.495180  0.492347
27        random_forest    shuffled_val        Plate_5  0.490360  0.491264
24        random_forest    shuffled_val     all_plates  0.498269  0.499568
21              xgboost   shuffled_test        Plate_3  0.512948  0.537370
22              xgboost   shuffled_test  Plate_3_prime  0.518433  0.544662
23              xgboost   shuffled_test        Plate_5  0.477578  0.517598
20              xgboost   shuffled_test     all_plates  0.505839  0.534267
17              xgboost  shuffled_train        Plate_3  0.502412  0.507167
18              xgboost  shuffled_train  Plate_3_prime  0.505074  0.506700
19              xgboost  shuffled_train        Plate_5  0.504313  0.514414
16              xgboost  shuffled_train     all_plates  0.503524  0.508837
13              xgboost    shuffled_val        Plate_3  0.491196  0.501830
14              xgboost    shuffled_val  Plate_3_prime  0.492390  0.502115
15              xgboost    shuffled_val        Plate_5  0.489346  0.492051
12              xgboost    shuffled_val     all_plates  0.491036  0.499544

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: logistic_regression: mean shuffled accuracy=0.4992, mean shuffled f1=0.4963 over 12 rows
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: xgboost: mean shuffled accuracy=0.4995, mean shuffled f1=0.5139 over 12 rows
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: random_forest: mean shuffled accuracy=0.5043, mean shuffled f1=0.5216 over 12 rows

In [7]:
# Cell 7: optional persistence of comparison tables

out_dir = pathlib.Path("model_evaluation_data_ensemble")
out_dir.mkdir(exist_ok=True)

logger.info(f"Saving ensemble comparison tables to {out_dir}...")

test_comparison.to_parquet(out_dir / "ensemble_test_allplates.parquet", index=False)
plate_comparison.to_parquet(out_dir / "ensemble_test_per_plate.parquet", index=False)
summary_all.to_parquet(out_dir / "ensemble_train_val_test.parquet", index=False)
shuffled_summary.to_parquet(out_dir / "ensemble_shuffled_summary.parquet", index=False)

logger.info("Finished saving ensemble comparison tables.")

2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: Saving ensemble comparison tables to model_evaluation_data_ensemble...
2025-12-07T07:32:22 [evaluate_12_07_07_30_ensemble_eval] INFO: Finished saving ensemble comparison tables.